backend:
  name: git-gateway
  branch: main

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "properties"
    label: "Ev Elanları"
    folder: "content/properties"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Başlıq", name: "title", widget: "string" }
      - { label: "Qiymət", name: "price", widget: "string" }
      - { label: "Şəkil", name: "image", widget: "image" }
      - { label: "Məlumat", name: "body", widget: "markdown" }